mytodo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('todo/', include('todo.urls')),
]

todo/urls.py
from django.urls import path

from . import views


app_name = 'todo'

urlpatterns = [
    path('', views.TodoListView.as_view(), name='index'),
    path('create/', views.TodoCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', views.TodoDeleteView.as_view(), name='delete'),
]

todo/models.py
from django.db import models


class Todo(models.Model):
    content = models.CharField(max_length=100)

todo/views.py
from django.views.generic import ListView, CreateView, DeleteView
from django.urls import reverse_lazy

from .models import Todo


class TodoListView(ListView):
    model = Todo
    template_name = 'todo/todo_index.html'


class TodoCreateView(CreateView):
    model = Todo
    fields = '__all__'
    template_name = 'todo/todo_form.html'
    success_url = reverse_lazy('todo:index')


class TodoDeleteView(DeleteView):
    model = Todo
    template_name = 'todo/todo_confirm_delete.html'
    success_url = reverse_lazy('todo:index')

templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TODO LIST</title>
</head>
<body>
    <h1>TODO LIST</h1>
    <a href="{% url 'todo:create' %}">작성하기</a>
    {% block content %}
    {% endblock %}
</body>
</html>

todo/templates/todo/todo_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <h2>정말로 삭제하시겠습니까?</h2>
    <form action="." method="POST">
        {% csrf_token %}
        <input type="submit" value="예">
    </form>

{% endblock %}

todo/templates/todo/todo_form.html
{% extends 'base.html' %}

{% block content %}

    <form action="{% url 'todo:create' %}" method="POST">
        <label for="todo">Todo</label>
        <input name="content" type="text">
        <input type="submit" value="작성">
        {% csrf_token %}
    </form>

{% endblock %}

todo/templates/todo/todo_index.html
{% extends 'base.html' %}

{% block content %}

    {% for todo in todo_list %}
        <p>{{ todo.content }} <a href="{% url 'todo:delete' todo.pk %}">삭제</a></p>
    {% empty %}
        <p>아직 할 일이 없습니다.</p>
    {% endfor %}

{% endblock %}